name: Github Actions Sample

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "挨拶"
        run: echo "Nice to meet you!!"

      - name: "名前を言う"
        run: echo "My name is Taro!!"

      - name: "趣味を話す"
        run: echo "I love programming!!"
  echo_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "別れの挨拶をする"
        run: echo "Good Bye!!"